Running suite(s): Default
84%: Checks: 13, Failures: 1, Errors: 1
public.c:35:F:Public:A_invalid_main_var:0: Assertion 'invalid_program("int main; def int foo(int a) { return 0; }")' failed
private.c:5:E:Private:A_null_tree:0: (after this point) Received signal 11 (Segmentation fault)
